name: CI

on:
  push:
    branches:
      - main
      - master
      - 'v*'
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true  

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm lint:js
        working-directory: packages/ember-cli-code-coverage
      - run: pnpm test
