name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile
      - run: yarn lint:js
        working-directory: packages/ember-cli-code-coverage
      - run: yarn test
